name: dastaan_e_shahadat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+19
environment:
  sdk: ">=2.17.0 <4.0.0" # Updated to a more recent version for better compatibility

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  global_configuration: ^2.0.0
  google_fonts: 6.1.0
  velocity_x: ^4.1.2
  get_storage: ^2.0.3
  fluttertoast: ^8.0.9
  awesome_dialog: ^3.2.0
  change_app_package_name: ^1.1.0
  flutter_html: ^3.0.0-alpha.3
  cached_network_image: ^3.3.1
  flutter_easyloading: ^3.0.3
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^7.4.0
  http: ^1.2.1
  carousel_slider: ^4.1.1
  awesome_bottom_bar: any
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^4.3.0
  url_launcher: ^6.1.0
  flutter_barcode_scanner: ^2.0.0
  flutter_inappwebview: ^5.4.0
  upgrader: ^9.0.0
  assets_audio_player: ^3.1.1
  readmore: ^2.2.0
  youtube_player_iframe: ^2.2.2
  scrollable_positioned_list: ^0.3.1
  firebase_dynamic_links: ^5.4.16
  sign_in_with_apple: ^4.3.0
  dropdown_search: ^3.0.1
  location: ^5.0.3
  flutter_beacon: ^0.5.1
  flutter_speed_dial: ^6.0.0
  photo_view: ^0.14.0
  permission_handler: ^9.2.0
  cupertino_icons: ^1.0.4
  firebase_core_platform_interface: ^5.0.0
  firebase_core: ^2.26.0
  flutter_cache_manager: ^3.3.0
  flutter_downloader: ^1.11.7
  path_provider: ^2.0.11
  firebase_messaging: ^14.7.18
  flutter_local_notifications: ^9.3.0
  flutter_native_splash: ^2.3.10
#  sms_autofill:
#    git:
#      url: https://github.com/jaumard/sms_autofill
#      ref: master

  flutter_callkit_incoming: ^2.0.4
#  flutter_sms: ^2.3.3
#  readsms: ^0.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/images/
    - assets/fonts/
    - assets/data_files/
    - data/assets/
    - data/assets/nearby/
    - data/assets/audios/
    - data/assets/beacons/
    - data/assets/beacons/original/
    - data/assets/beacons/original/sounds/
    - data/assets/beacons/original/sounds/hindi/
    - data/assets/beacons/original/sounds/english/
    - data/assets/beacons/original/sounds/punjabi/
    - data/assets/images/categorytype-icons/
    - data/assets/images/category-icons/
    - data/assets/outlinkedimages/
    - data/assets/static/locations/
    - data/assets/static/locations/gallery/
    - data/assets/static/locations/gallery/800800/
    # Add the rest of your asset directories

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf

flutter_native_splash:
  background_image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
